# Function s

In [2]:
# square of an odd number

In [3]:
import numpy as np
def odd(n):
    a=np.arange(n)
    c=(a[a%2==1])
    k=c**2
    print(k)

In [4]:
#2 Import Null vector in numpy

In [6]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#3 vector ranging 10 to 49

In [8]:
import numpy as np
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#4  Find shape of the array in 3

In [11]:
import numpy as np
x=np.arange(10,50)
print(x.shape)

(40,)


In [12]:
#5 Find type of an array in Q3

In [14]:
import numpy as np
x=np.arange(10,50)
print(x.dtype)

int32


In [15]:
#6Print the numpy version and configuration

In [17]:
import numpy as np
np.version.version

'1.18.5'

In [18]:
# 7 dimension of an array in Q3

In [19]:
import numpy as np
x=np.arange(10,50)
print(x.ndim)

1


In [20]:
#8 Create a boolean array with all true values

In [21]:
import numpy as np
x=np.array([2,3,4,5,6,7,8,9,10],dtype=bool)
print(x)

[ True  True  True  True  True  True  True  True  True]


In [22]:
# 9Create a two dimensional array

In [26]:
import numpy as np
x=np.arange(50).reshape(2,25)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [27]:
#10  Create a three dimensional array

In [35]:
import numpy as np
x=np.arange(64).reshape(4,4,4)
#print(x)

In [34]:
#11Revese a vector

In [40]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.arange(25)
print(x)
b=x[::-1]
c=np.flipud(y)
print(b)
print(c)

[1 2 3 4 5 6]
[6 5 4 3 2 1]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]


In [41]:
 #12  Create a null vector of size 10 but 5th value is 1

In [44]:
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [45]:
#13 Create a 3*3 identity matrix

In [46]:
import numpy as np
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
 # 14 arr=np.array([1 ,2, 3, 4, 5]) convert fron int into float

In [49]:
import numpy as np
arr=np.array([1,2,3,4,5])
a=arr.astype(float)
print(arr.dtype)
print(a)

int32
[1. 2. 3. 4. 5.]


In [50]:
# 15 Multiply matrix 1 with 2

In [53]:
import numpy as np
arr1=np.array([[1.,2.],[4.,5.]])
arr2=np.array([[0.,1.],[7.,12]])
a=np.dot(arr1,arr2)
print(a)

[[14. 25.]
 [35. 64.]]


In [54]:
#16 Make an array by comparing values of two matrices

In [55]:
import numpy as np
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12]])
b=np.concatenate((arr1,arr2),axis=1)
print(b)

[[ 1.  2.  3.  0.  4.  1.]
 [ 4.  5.  6.  7.  2. 12.]]


In [56]:
 # 17 Extract all odd number from 0 to 9

In [67]:
import numpy as np
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12]])
odd1=(arr1[arr1%2==1])
odd2=(arr2[arr2%2==1])
print(odd1)
print(odd2)

[1. 3. 5.]
[1. 7.]


In [59]:
#18 comparing two arrays

In [63]:
import numpy as np
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12]])
print("arr1 >arr2")
print(np.greater(arr1,arr2))
print("arr1<arr2")
print(np.less(arr1,arr2))


arr1 >arr2
[[ True False  True]
 [False  True False]]
arr1<arr2
[[False  True False]
 [ True False  True]]


In [68]:
# 19replace all odd numbers with -1 in the example 18

In [73]:
import numpy as np
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12]])
odd1=(arr1[arr1%2==1])
odd2=(arr2[arr2%2==1])
print(odd1)
print(odd2)
arr1[arr1%2==1]=-1
#arr1[odd1]=-1
print(arr1)
arr2[arr2%2==1]=-1
print(arr2)

[1. 3. 5.]
[1. 7.]
[[-1.  2. -1.]
 [ 4. -1.  6.]]
[[ 0.  4. -1.]
 [-1.  2. 12.]]


In [74]:
#20 # replace the values from an arry5,6,7,8 by 12

In [80]:
import numpy as np
arr=np.arange(10)
print(arr)
arr[4:8]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 12 12 12 12  8  9]


In [81]:
#21 Create a 2d array with 1 in the border and 0 inside

In [89]:
import numpy as np
arr=np.ones((5,5))
print(arr)
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [90]:
#22 2d array , replace the value 5 to 12

In [104]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(arr)
arr[1,1]=12
print(arr)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [95]:
#23 Array 3d ,Convert all the values of first array to 64

In [108]:
import numpy as np
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)
arr3d[::,0]=64
print(arr3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[64 64 64]
  [ 4  5  6]
  [ 7  8  9]]]


In [109]:
#24 Make a 2 dim array with values from 0 to 9 and slice the first array from it

In [116]:
import numpy as np
arr=np.arange((10)).reshape(2,5)
print(arr)
print(arr[0])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


In [117]:
#25 Make a two dimensional array and slice 2 value of the second array

In [127]:
import numpy as np
arr=np.arange(10).reshape(2,5)
print (arr[1,:])
print(arr[1,2])

[5 6 7 8 9]
7


In [128]:
#26 Make a two dimensional array but slice out third colum wut first two rows

In [136]:
import numpy as np
arr=np.arange(10).reshape(2,5)
print(arr)
print(arr[:,[3]])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[3]
 [8]]


In [137]:
#27 Creste a 10*10 array with random values and find max and min values

In [146]:
import numpy as np
x =np. random.randint(100, size=(10, 10))
print(x)
mini=np.min(x)
maxi=np.max(x)
print(mini)
print(maxi)

[[45 77 85 70 50 49 62 32 30 37]
 [44 91 35 46 62 16 85 46 71 36]
 [71 51 92 51 72 20 62 36 33 76]
 [93 48 68  0 10 67 87 60 76 81]
 [52 30 25  4 39 81 37 73 47 23]
 [68 24 47 56  6 75 51 74 20 94]
 [80 54 55 35 78 21 17  8 50  6]
 [12  3 43 58 61 41 24 40 45 82]
 [41 60 15 36 63 29 84 10 81 66]
 [34 75 33 78 41 91 98  0 25 64]]
0
98


In [147]:
# 28  Common item between two arrrays

In [151]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(a,b)
c=np.intersect1d(a,b)
print(c)

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]
[2 4]


In [152]:
#29 Find the number of positions where the common value intersect

In [154]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(a,b)
ab, a_ind, b_ind = np.intersect1d(a, b, return_indices=True)
a_ind,b_ind

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]


(array([1, 5], dtype=int64), array([1, 5], dtype=int64))

In [155]:
#30

In [156]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-5.19501250e-01  8.40532335e-04 -1.18494189e+00  5.65947228e-01]
 [-1.71665134e-01  4.87313823e-01 -1.68419098e-01 -2.11991039e-02]
 [ 1.46618302e+00  1.36825078e+00 -1.08727461e+00  3.36864686e-01]
 [ 5.65983597e-01 -4.04526106e-01  1.37742879e+00 -1.70492870e+00]
 [ 1.12693311e-01  9.90089754e-01  1.22550332e+00 -4.39080251e-01]
 [-4.50241939e-01 -4.67430605e-01 -5.82183650e-03  2.50607154e-01]
 [-1.11427439e+00  2.25928673e+00 -5.74780331e-01 -2.34047575e-01]]


# Difficulty level Hard

In [157]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [158]:
import numpy as np
x=np.arange(15).reshape(5,3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [159]:
#32Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [160]:
import numpy as np
x=np.arange(16).reshape(2,2,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [161]:
#33 Swap the axis that has createdin Q,32

In [166]:
import numpy as np
x=np.arange(16).reshape(2,2,4)
np.swapaxes(x,2,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [167]:
#34 Create an array of size 10, and find the square root of every element in the array,
#if the values less than 0.5,replace them with 0

In [1]:
import numpy as np
x=np.arange(10)
b=np.sqrt(x)
print(b)
b[b<0.5]=0
print(b)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [2]:
# 35 Create two arrays of range 12 and compare the elements and make
#another array which contain the maximun of the two arrays

In [42]:
import numpy as np
a=np.random.randint(low=0, high=20, size=12)
b=np.random.randint(low=0, high=20, size=12)
#print(a)
#print(b)
c=np.maximum(a,b)
#print(c)
np.sort(c)

array([15,  9, 13,  7, 16, 18, 13, 16, 11, 17, 17, 10])

In [32]:
##35  Find uniques  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) and sort
#them out

In [38]:
import numpy as np
np.unique(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
#print(a)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [43]:
#36 Remove elements of an array a=[1 2 3 4 5] b=[4 5 6 7 8] that are present in b

In [47]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)
#print(z)

array([1, 2, 3, 4])

In [48]:
#37 Following is the input NumPy array delete column two and insert following new column 
#in its place.
#sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
#newColumn = numpy.array([[10,10,10]])

In [65]:
import numpy as np
alpha=np.array([[34,43,73],[82,22,12],[53,94,66]])
alpha
alpha[:,1]=[10,10,10]
#out=np.delete(alpha,1,1)
#out
alpha

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [ ]:
#38 Find the dot product of two matrices

In [66]:
import numpy as np
m1=np.array([[34,43,73],[82,22,12],[53,94,66]])
m2=np.array([10,10,10])
m3=np.dot(m1,m2)
m3

array([1500, 1160, 2130])

In [67]:
#39 Generate a matrix of 20 random values and find its cummulative sum

In [75]:
import numpy as np
M=np.random.randint(low=0, high=20, size=20)
M
np.cumsum(M,axis=0)


AxisError: axis 1 is out of bounds for array of dimension 1